# Generated by Django 5.1.3 on 2024-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_casos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casuistica',
            name='agente_asignado',
        ),
        migrations.AddField(
            model_name='casuistica',
            name='agentes_asignados',
            field=models.ManyToManyField(blank=True, to='panel_casos.agente'),
        ),
    ]
