# Generated by Django 5.1.3 on 2024-11-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_casos', '0002_remove_casuistica_agente_asignado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='carga_trabajo',
        ),
        migrations.RemoveField(
            model_name='casuistica',
            name='agentes_asignados',
        ),
        migrations.AddField(
            model_name='casuistica',
            name='agentes',
            field=models.ManyToManyField(blank=True, related_name='casuisticas', to='panel_casos.agente'),
        ),
    ]
