# Generated by Django 5.1.3 on 2024-11-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_casos', '0003_remove_agente_carga_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='carga_trabajo',
            field=models.IntegerField(default=0),
        ),
    ]
